### ISSUE TITLE
Serialization of Option<Tuple2<X, Y>> as bean field fails.

### ISSUE THREAD

**Issue by jezovuk** [vavr-io/vavr-jackson#116]
I have a bean property of type Option<Tuple2<LocalDateTime, LocalDateTime>>. Serialization fails with serializer trying to cast Tuple2 into LocalDateTime. Problem seems to be in OptionSerializer.emulatedJavaType(JavaType, TypeFactory). I think it should return type (or something based on it), rather than its first contained type.

Stack trace (root cause):

`Caused by: java.lang.ClassCastException: io.vavr.Tuple2 cannot be cast to java.time.LocalDateTime
	at com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer.serialize(LocalDateTimeSerializer.java:34)
	at io.vavr.jackson.datatype.serialize.ValueSerializer.serialize(ValueSerializer.java:63)
	at io.vavr.jackson.datatype.serialize.OptionSerializer.serialize(OptionSerializer.java:45)
	at io.vavr.jackson.datatype.serialize.OptionSerializer.serialize(OptionSerializer.java:30)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:704)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:689)
	... 42 common frames omitted`

**Comment by ruslansennov** [comment]
Hi @jezovuk 
I can't reproduce the problem. Which version of `vavr-jackson` are you use?

```java
@Test
public void kekeke1() throws Exception {
    Option<Tuple2<List<Integer>, List<Integer>>> option = Option.some(Tuple.of(List.of(1), List.of(2)));
    String json = mapper().writeValueAsString(option);
    System.out.println(json);  // [[1],[2]]
    Option<Tuple2<List<Integer>, List<Integer>>> restored = mapper().readValue(json, new TypeReference<Option<Tuple2<List<Integer>, List<Integer>>>>() {});
    System.out.println(restored);  //  Some((List(1), List(2)))
    System.out.println(restored.equals(option));  //  true
}

@Test
public void kekeke2() throws Exception {
    LocalDateTime d1 = new LocalDateTime(2017, 1, 1, 1, 1);
    LocalDateTime d2 = new LocalDateTime(2017, 2, 2, 2, 2);
    Option<Tuple2<LocalDateTime, LocalDateTime>> option = Option.some(Tuple.of(d1, d2));
    ObjectMapper mp = mapper().registerModule(new JodaModule());
    String json = mp.writeValueAsString(option);
    System.out.println(json);  //  [[2017,1,1,1,1,0,0],[2017,2,2,2,2,0,0]]
    Option<Tuple2<LocalDateTime, LocalDateTime>> restored = mp.readValue(json, new TypeReference<Option<Tuple2<LocalDateTime, LocalDateTime>>>() {});
    System.out.println(restored);  //  Some((2017-01-01T01:01:00.000, 2017-02-02T02:02:00.000))
    System.out.println(restored.equals(option));  //  true
}
```

**Comment by jezovuk** [comment]
Using vavr and vavr-jackson 0.9.1. Your test does pass. However, it fails if option is used as pojo field.
Failing test:

```java
    @Test
    public void kekeke3() throws Exception {
        jacksonObjectMapper().writeValueAsString(new Kekeke());
    }

    private static final class Kekeke {
        Option<Tuple2<LocalDateTime, LocalDateTime>> x = Option.some(Tuple.of(LocalDateTime.of(2017, 1, 1, 1, 1), LocalDateTime.of(2017, 2, 2, 2, 2)));

        public Option<Tuple2<LocalDateTime, LocalDateTime>> getX() {
            return x;
        }
    }
```

BTW, LocalDateTime is Java8 one in my case, not Joda Time, but that is probably irrelevant.

**Comment by ruslansennov** [comment]
Something strange. This test pass the serialization and fails deserialization. Which version of Jackson are you using?
```java
@Test
public void kekeke3() throws Exception {
    String json = mapper().writeValueAsString(new Kekeke());
    System.out.println(json);  // {"x":[{"year":2017,"monthValue":1, ...
    Kekeke restored = mapper().readValue(json, Kekeke.class);
    System.out.println(restored.getX()); // com.fasterxml.jackson.databind.JsonMappingException
}
```

**Comment by jezovuk** [comment]
Using Jackson 2.8.10. Your test fails serialization for me (same ClassCastException as before). However, if (declared) type of Kekeke.x is changed to `Option<?>`, everything works ok (both serialization and deserialization). I'll try the latest Jackson version.

**Comment by ruslansennov** [comment]
We use 2.7.2 and 2.8.4 Jackson versions for `vavr-jackson` unit test (see [travis](https://github.com/vavr-io/vavr-jackson/blob/master/.travis.yml#L13)). Both serializes fine for me. Version 2.8.10 also passes...

**Comment by jezovuk** [comment]
Tried Jackson 2.9.2, no luck.

Here is entire (minimal) test case:

```java
package xena.common.jackson;

import org.junit.Test;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.vavr.Tuple;
import io.vavr.Tuple2;
import io.vavr.control.Option;
import io.vavr.jackson.datatype.VavrModule;

public class VavrJacksonOptionTest {

    private static class Pojo {
        private Option<Tuple2<String, String>> x = Option.of(Tuple.of("A", "B"));

        public Option<Tuple2<String, String>> getX() {
            return x;
        }
        public void setX(Option<Tuple2<String, String>> x) {
            this.x = x;
        }
    }

    @Test
    public void test() throws Exception {
        final ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new VavrModule());
        final String str = mapper.writeValueAsString(new Pojo());
        System.out.println(str);
    }

}
```

Resulting exception trace:

```
com.fasterxml.jackson.databind.JsonMappingException: io.vavr.Tuple2 cannot be cast to java.lang.String (through reference chain: xena.common.jackson.VavrJacksonOptionTest$Pojo["x"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3207)
	at xena.common.jackson.VavrJacksonOptionTest.test(VavrJacksonOptionTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
Caused by: java.lang.ClassCastException: io.vavr.Tuple2 cannot be cast to java.lang.String
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
	at io.vavr.jackson.datatype.serialize.ValueSerializer.serialize(ValueSerializer.java:63)
	at io.vavr.jackson.datatype.serialize.OptionSerializer.serialize(OptionSerializer.java:45)
	at io.vavr.jackson.datatype.serialize.OptionSerializer.serialize(OptionSerializer.java:30)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	... 29 more
```

Replacing `public Option<Tuple2<String, String>> getX()` with `public Option<?> getX()` makes it work.

Using JDK8u144. Test run manually, from Eclipse.

**Comment by jezovuk** [comment]
Also tried Jackson 2.7.2 and 2.8.4, same problem.

**Comment by ruslansennov** [comment]
Got it. I created a new clean project and the problem was reproduced.

**Comment by jezovuk** [comment]
Yay! Thanks for the effort.

**Comment by ruslansennov** [comment]
@jezovuk thanks for reporting. 
This issue clashes with #114 and shows that all serializes must be reworked :(

**Comment by jezovuk** [comment]
So what is the state of this now? Both this issue and #114 are closed. Is there something else to do/fix?

**Comment by ruslansennov** [comment]
@jezovuk both issues fixed for `Lazy` and `Option`

**Comment by jezovuk** [comment]
Thanks. Looking forward to next release 😃
