### ISSUE TITLE
Comparator in instance of TreeMap which has been deserialized from JSON is not java.io.Serializable

### ISSUE THREAD

**Issue by Boerrild** [vavr-io/vavr-jackson#120]
When using vavr-jackson (0.9.2) to deserialize a TreeMap from JSON I get an instance back where the comparator apparently is not implementing "java.io.Serializable". Looking into the code the culprit seems to be the io.vavr.jackson.datatype.deserialize.MaplikeDeserializer that fails to provide a Serializable lambda reference.

The following JUnit4 test proves the case and suggests a correction:
```package com.inpay.psp.billing.state;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.vavr.collection.TreeMap;
import io.vavr.jackson.datatype.VavrModule;
import org.junit.Assert;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.NotSerializableException;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.Comparator;

public class VarvSerializationTest {

    /**
     * Test that proves that io.varv.collection.TreeMap cannot be deserialized after JSON deserialization
     */
    @Test
    public void nonSerializableTreeMapTest() throws Exception {

        // SETUP
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        ObjectOutputStream outputStream = new ObjectOutputStream(byteArrayOutputStream);

        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new VavrModule());

        //given:
        TreeMap treeMap = TreeMap.empty();

        // WHEN serialized and de-serialized with jackson
        TreeMap jsonDeSerialized = objectMapper.readValue(objectMapper.writeValueAsBytes(treeMap), TreeMap.class);

        // AND serialized with java.io
        try {
            outputStream.writeObject(jsonDeSerialized);
        } catch (NotSerializableException e) {

        // THEN a NotSerializableException is thrown:

            //java.io.NotSerializableException: TestHelper$$Lambda$1/654845766
            //
            //  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
            //  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
            //  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
            //  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
            //  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
            //  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
            //  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
            //  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
            //  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
            //  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
            //  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
            //  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
            //  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
            //  at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
            //  at com.inpay.psp.billing.state.SerializationTest.nonSerializableLambdaBasedKeyComparatorTest(SerializationTest.java:33)
            //   ...
        }
    }

    /** Test that proves that the lambda expression used by io.vavr.jackson.datatype.deserialize.MaplikeDeserializer is NOT serializable */
    @Test
    public void nonSerializableLambdaBasedKeyComparatorTest() throws Exception {

        // SETUP
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        ObjectOutputStream outputStream = new ObjectOutputStream(byteArrayOutputStream);

        // GIVEN
        TreeMap treeMap = TreeMap.empty(nonSerializableLambdaBasedKeyComparator());

        // WHEN serializing with java
        try {
            outputStream.writeObject(treeMap);
            Assert.fail("Expected a NotSerializableException");
        } catch (NotSerializableException e) {
            // THEN a NotSerializableException is thrown:
            //
            //  java.io.NotSerializableException: TestHelper$$Lambda$1/654845766
            //  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
            //  ...
        }
    }

    public static Comparator<Object> nonSerializableLambdaBasedKeyComparator() {
        return (o1, o2) -> ((Comparable) o1).compareTo(o2);
    }

    /** Test that proves that the lambda expression used by io.vavr.jackson.datatype.deserialize.MaplikeDeserializer could be made serializable */
    @Test
    public void serializableLambdaBasedKeyComparatorTest() throws Exception {
        // SETUP
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        ObjectOutputStream outputStream = new ObjectOutputStream(byteArrayOutputStream);

        // GIVEN
        TreeMap treeMap = TreeMap.empty(serializableLambdaBasedKeyComparator());

        // WHEN serializing with java
        outputStream.writeObject(treeMap);

        // THEN no exception is thrown
    }

    public static Comparator<Object> serializableLambdaBasedKeyComparator() {
        return (Comparator<Object> & Serializable) (o1, o2) -> ((Comparable) o1).compareTo(o2);
    }

}

**Comment by ruslansennov** [comment]
thank you
